### ISSUE TITLE
compatibly issues with RedHat os_family systems

### ISSUE THREAD

**Issue by grimsbane** [salt-formulas/salt-formula-linux#134]
Hi,
it looks that kernel.sls, hugepages.sls, iommu.sls and grub.sls have compatibly issues with RedHat os_family systems e.g Centos.

`update-grub` is not available RedHat os_family systems
```
linux/systemgrub.sls:
[..]
grub_update:
  cmd.wait:
  - name: update-grub
[..]
```
In RedHat os_family systems we use `grub2-mkconfig` to generate grub.cfg. grub2-mkconfig does not include configuration files in /etc/default/grub.d.
```
grub_d_directory:
  file.directory:
    - name: /etc/default/grub.d
    - user: root
    - group: root
    - mode: 755
    - makedirs: True
```

To solve this issue we have a couple of options. In general i like the idea that we have config files e.g 90-isolcpu.cfg, 90-isolcpu.cfg or 90-iommu.cfg separated in /etc/default/grub.d. Unfortunately `grub2-mkconfig` (in RedHat os) does not include this files to /etc/default/grub. But this could be archived by sourcing this files in /etc/default/grub.d/* and would also mean it is not necessary append /etc/default/grub by all of this different kernel settings. Another pro is the fact that we don't have to split a lot of code to Debian/RedHat.

Please see my merge request
