### ISSUE TITLE
Issue in linux/system/profile.sls, profile scripts always recreated

### ISSUE THREAD

**Issue by grimsbane** [salt-formulas/salt-formula-linux#179]
Hi,

it seems there is an issue in linux/system/profile.sls, if we manage profiles we always see and change. This is caused by cleanup directory/create files:

```
profile.d_clean:
  file.directory:
  - name: /etc/profile.d
  - clean: true
  - exclude_pat: 'E@^((?!salt_profile*).)*$'

{%- if system.profile|length > 0 %}

{%- for name, script in system.profile.items() %}
profile.d_script_{{ name  }}:
    file.managed:
    - name: /etc/profile.d/salt_profile_{{ name }}{%if name.split('.')|length == 1 %}.sh{% endif %}
    - source:
      - salt://linux/files/etc_profile_{{ name }}
      - salt://linux/files/etc_profile
    - template: jinja
    - defaults:
          script: {{ script|yaml }}
    - require_in:
      - service: profile.d_clean
{% endfor %}
```

In general this can be fixed by add an required_in what is already set, but as we can see it should mention file not service:

wrong:
```
    - require_in:
      - service: profile.d_clean
```

 right:
```
    - require_in:
      - file: profile.d_clean
```
