### ISSUE TITLE
feature - configure transparent_hugepage in system kernel

### ISSUE THREAD

**Issue by nick-metz-fhe3** [salt-formulas/salt-formula-linux#186]
Hi,

it should be possible to configure transparent_hugepage with kernel parameter in grub.conf.

```
linux:
  system:
    enabled: true
    kernel:
      transparent_hugepage: never
```

will add an merge request for this feature.

**Comment by grimsbane** [comment]
hm.. seems this is already possible with boot_options, but makes it hard to overwrite a single boot opt if multiple bootops defined.

```
    kernel:
      isolcpu: 1,2,3,4
      elevator: deadline
      boot_options:
        - transparent_hugepage=never
```
